// Mock data for the portfolio

export const mockData = {
  profile: {
    name: "Ziaur Rahman",
    title: "Graphic Design Specialist",
    tagline: "Crafting Stunning Book Cover Designs",
    bio: "I'm a passionate graphic designer specializing in book cover mockups and design. With years of experience in the publishing industry, I create visually compelling covers that capture the essence of every story. My designs have helped hundreds of authors make their books stand out on Amazon KDP and other platforms.",
    bio2: "I create stunning book cover mockups that bring stories to life. With years of experience in graphic design, I specialize in crafting unique, eye-catching designs that stand out on Amazon KDP and beyond. Each mockup is carefully designed to capture the essence of your story.",

    email: "alex.martinez@bookdesigns.com",
    phone: "+1 (555) 123-4567",
    location: "New York, USA",
    experience: "8+ years in graphic design",
    projectsCompleted: "500+ Book Covers",
  },

  skills: [
    "Book Cover Design",
    "Typography",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Mockup Creation",
    "Brand Identity",
    "Color Theory",
    "Layout Design",
    "Digital Art",
    "Print Design",
  ],

  bookMockups: [
    {
      id: 1,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 2,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/qMBtkfNM/book-mockup2.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 3,
      title: "Botanical Book Cover",
      description: "Minimalist design with floral elements",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-3",
      category: "Softcover",
    },
    {
      id: 4,
      title: "Classic White Edition",
      description: "Timeless design on wooden texture",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-4",
      category: "Hardcover",
    },
    {
      id: 5,
      title: "Modern Notebook Style",
      description: "Contemporary notebook mockup design",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-5",
      category: "Notebook",
    },
    {
      id: 6,
      title: "Open Book Layout",
      description: "Perfect for interior page mockups",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-6",
      category: "Interior",
    },
    {
      id: 7,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 8,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 9,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 10,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 11,
      title: "Botanical Book Cover",
      description: "Minimalist design with floral elements",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-3",
      category: "Softcover",
    },
    {
      id: 12,
      title: "Classic White Edition",
      description: "Timeless design on wooden texture",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-4",
      category: "Hardcover",
    },
    {
      id: 13,
      title: "Modern Notebook Style",
      description: "Contemporary notebook mockup design",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-5",
      category: "Notebook",
    },
    {
      id: 14,
      title: "Open Book Layout",
      description: "Perfect for interior page mockups",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-6",
      category: "Interior",
    },
    {
      id: 15,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 16,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 17,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 18,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 19,
      title: "Botanical Book Cover",
      description: "Minimalist design with floral elements",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-3",
      category: "Softcover",
    },
    {
      id: 20,
      title: "Classic White Edition",
      description: "Timeless design on wooden texture",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-4",
      category: "Hardcover",
    },

    {
      id: 21,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 22,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 23,
      title: "Botanical Book Cover",
      description: "Minimalist design with floral elements",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-3",
      category: "Softcover",
    },
    {
      id: 24,
      title: "Classic White Edition",
      description: "Timeless design on wooden texture",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-4",
      category: "Hardcover",
    },
    {
      id: 25,
      title: "Modern Notebook Style",
      description: "Contemporary notebook mockup design",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-5",
      category: "Notebook",
    },
    {
      id: 26,
      title: "Open Book Layout",
      description: "Perfect for interior page mockups",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-6",
      category: "Interior",
    },
    {
      id: 27,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 28,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 29,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 30,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 31,
      title: "Botanical Book Cover",
      description: "Minimalist design with floral elements",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-3",
      category: "Softcover",
    },
    {
      id: 32,
      title: "Classic White Edition",
      description: "Timeless design on wooden texture",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-4",
      category: "Hardcover",
    },
    {
      id: 33,
      title: "Modern Notebook Style",
      description: "Contemporary notebook mockup design",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-5",
      category: "Notebook",
    },
    {
      id: 34,
      title: "Open Book Layout",
      description: "Perfect for interior page mockups",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-6",
      category: "Interior",
    },
    {
      id: 35,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 36,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 37,
      title: "Premium Hardcover Design",
      description: "Professional hardcover mockup with marble backdrop",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-1",
      category: "Hardcover",
    },
    {
      id: 38,
      title: "Elegant Book Mockup",
      description: "Clean and minimalist hardcover design",
      image: "https://i.ibb.co.com/bRWG41Ht/book-mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-2",
      category: "Hardcover",
    },
    {
      id: 39,
      title: "Botanical Book Cover",
      description: "Minimalist design with floral elements",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-3",
      category: "Softcover",
    },
    {
      id: 40,
      title: "Classic White Edition",
      description: "Timeless design on wooden texture",
      image: "/book_mockup.jpg",
      amazonLink: "https://www.amazon.com/kdp/your-product-4",
      category: "Hardcover",
    },
  ],

  testimonials: [
    {
      id: 1,
      name: "Sarah Johnson",
      role: "Author",
      content:
        "The book cover mockups are absolutely stunning! They helped my book stand out on Amazon and increased my sales significantly.",
      rating: 5,
    },
    {
      id: 2,
      name: "Michael Chen",
      role: "Publisher",
      content:
        "Professional quality mockups with incredible attention to detail. Highly recommend for any author or publisher!",
      rating: 5,
    },
    {
      id: 3,
      name: "Emma Davis",
      role: "Self-Published Author",
      content:
        "These mockups made my book look incredibly professional. The designs are unique and really capture the essence of the story.",
      rating: 5,
    },
  ],
};
