"use client";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import NavBar from "@/components/pages/home/Navbar";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <div className={`${pathname === "/login" && "hidden"}`}>
          <NavBar />
        </div>
        <div className={`${pathname === "/login" ? "" : "pt-15.75"}`}>
          {children}
        </div>

        <Toaster position="top-right" />
      </body>
    </html>
  );
}
